# Generated by Django 5.1.7 on 2025-03-30 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rocket_port_predictor', '0002_auto_20240319_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missioninput',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='missioninput',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
