# Generated by Django 5.1.7 on 2025-03-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocket_port_predictor', '0003_auto_20250330_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
        migrations.AlterField(
            model_name='missioninput',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='missioninput',
            name='launch_status',
            field=models.CharField(default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='missioninput',
            name='rocket_name',
            field=models.CharField(max_length=100),
        ),
    ]
